### ISSUE TITLE
The new default install location is not documented in Changes

### ISSUE THREAD

**Issue by dolmen** [briandfoy/PerlPowerTools#23]
The new default install location (`~/perlpowertools`) is not documented in the [`Changes`](../blob/master/Changes) file.

**Comment by briandfoy** [comment]
I didn't mean it to be. You see it in the Makefile.PL message.

**Comment by dolmen** [comment]
This assumes that the CPAN client shows Makefile.PL output. But `cpanm` doesn't.

**Comment by briandfoy** [comment]
I think that needs to be raised in cpanm. If we can't communicate things to users, that's a problem. No one is going to read the Changes file to find where things went anyway.

**Comment by miyagawa** [comment]
cpanm won't produce any output from configure tool - that is by design, and I can't special case PPT either.

The other option is to just die in `Makefile.PL` when INSTALL_BASE is not set - then cpanm can display `Configure failed: see ~/.cpanm/build.log for more details.` which is one step better.

Of course if you run `cpanm` with `-v` option it will show the output.

**Comment by miyagawa** [comment]
By the way,  `INSTALL_BASE` is still set if a user uses local::lib on their shell, which usually is set in their `$PATH`, and they *might* still have issues. I don't personally use it so I can live with this, but just a heads up.

**Comment by dolmen** [comment]
@miyagawa I don't think that local::lib environments will be corrupted because local::lib sets `INSTALL_BASE` via `PERL_MM_OPT` while [PPT's Makefile.PL](../blob/master/Makefile.PL#L48) directly looks into `@ARGV`.

**Comment by briandfoy** [comment]
I now look in PERL_MM_OPT to see if it's set there too.
