### ISSUE TITLE
git-formatted patch files are not always parsed properly

### ISSUE THREAD

**Issue by andygrundman** [briandfoy/PerlPowerTools#30]
Here is a sample patch file generated by git that causes ppt's patch to error with "Hmm... I can't seem to find a patch in there anywhere." This patch is against Net-SSLeay 1.72.

[Net-SSLeay-patch.txt](https://github.com/briandfoy/PerlPowerTools/files/109974/Net-SSLeay-patch.txt)

**Comment by klp2** [comment]
There are a few things going on here.

The regex used to detect a unified diff expecting nothing to trail the final '@@' of the hunk identifier.

Once that is fixed, it looks like if you run this like "patch inc/Module/Install/PRIVATE/Net/SSLeay.pm Net-SSLeay-patc-.txt" (ie 'patch <file-to-patch> <git-diff-file>') it has no problem detecting that its a unified diff with extras and applies the patch. However, if you try a typical "patch < Net-SSLeay-patch.txt" you get some output that looks like you were asked a question, but are never given a chance to respond and the script ends with a message that it is skipping the patch. This occurs because the script attempts to create a prompt to read STDIN, but STDIN is already open for the shell redirection that was done with '<'. 

I'll have a PR to fix those things once I can test it outside of linux, and that will bring it up to par with any other patch utility I've tested. I'm not sure if it makes sense to try to go a step further and attempt to detect git diff files and apply them without further user input.
