### ISSUE TITLE
brian's Guide to Solving Any Perl Problem

### ISSUE THREAD

**Issue by philiprbrenan** [briandfoy/PerlPowerTools#94]
"You might like to read brian's Guide to Solving Any Perl Problem." mentioned in the README does not seem to link to a page that contains this important information.

I do tell people, occasionally, now and then, that they should actualize their thought processes as words to load their subconcious with a definition of the problem to be solved in that dream like state achieved diurnally as the mind returns from sleep to wakefulness; in doing so I mention the teddy bear, but I can never find the location of this story and so my audience, no doubt, thinks that it is nothing but a Perl legend.

May I urge therefore that it would be helpful to have the story, and a photo of the bear in question, in its own github repo for easy reference so that its canon may long endure?

**Comment by briandfoy** [comment]
Thanks for catching this! Apparently all sorts of content I had at O'Reilly (my major publisher) has disappeared. I'm updating the README for this and all my other projects now.

Fixed in 92d6ca70c31240e2e57bf53f9f6da7017df0bc2d

In GitHub now: https://github.com/briandfoy/brians_guide_to_solving_any_perl_problem/blob/master/SolvingAnyPerlProblem.md

Latest stable home: https://briandfoy.github.io/brians-guide-to-solving-any-perl-problem/
